### ISSUE TITLE
Request for Initial Release to Indicate Available Versions

### ISSUE THREAD

**Issue by MingHuiLiu** [RevenantX/LiteEntitySystem#25]
Hello,  
I noticed that there are no releases published in this repository yet. Releasing a version would help users easily identify and access the available versions, especially for those not tracking the repository's commit history. Could you please publish a release to clearly indicate the latest stable version for users? This would make it much easier to integrate the project into other workflows.  
Thank you!

**Comment by RevenantX** [comment]
Added https://github.com/RevenantX/LiteEntitySystem/releases/tag/1.0.0
