### ISSUE TITLE
Support for different transports

### ISSUE THREAD

**Issue by menevis** [RevenantX/LiteEntitySystem#8]
Hello,

Firstly thanks for your effort to develop this project. Could you change it to transport-agnostic architecture? 
For example, you added LiteNetLib as default transport (I know it's tightly coupled now). If you can change this to a changeable transport structure. We as community can add all other transport systems like SteamNetwork, self-hosted relay, enet etc.

Regards

**Comment by RevenantX** [comment]
@menevis this is planned

**Comment by RevenantX** [comment]
done in 3e6c3e2 - Merge branch 'abstract_transport'
